"""
browser-use verification script template.
Copy this file, edit the task, and run it against your web app.

Usage:
  1. Activate the browser-use venv:
       source ~/.browser-use/activate.sh                  (macOS/Linux)
       source ~/AppData/Local/browser-use/activate.sh     (Windows/git-bash)
  2. Start your dev server (e.g. `npm run dev`)
  3. Edit TARGET_URL and TASK below
  4. Run: python this_file.py

The script:
  - Loads LLM config from config.py (auto-generated by setup.sh)
  - Creates a browser-use Agent with your task
  - Runs it headless and prints the structured result
"""
import asyncio
import sys
from pathlib import Path

# --- Load config (cross-platform venv detection) ---
# config.py lives in the venv root. Check both Windows and Unix paths.
for _venv in [
    Path.home() / "AppData" / "Local" / "browser-use",  # Windows
    Path.home() / ".browser-use",                        # macOS/Linux
]:
    if _venv.exists():
        sys.path.insert(0, str(_venv))
        break
else:
    print("❌ browser-use venv not found. Run setup.sh first.")
    sys.exit(1)

from config import API_KEY, BASE_URL, MODEL

from browser_use import Agent
from browser_use.llm import ChatOpenAI

# ============================================================
# EDIT THESE THREE VALUES
# ============================================================

TARGET_URL = "http://localhost:3000"

TASK = f"""
Go to {TARGET_URL} and verify the landing page:
1. Confirm the page loaded successfully
2. Find and report the page title
3. Check if there is a login or sign-in button
4. Click it and report what screen appears next
5. Report any errors or broken elements you observe

Return a structured report of your findings.
"""

MAX_STEPS = 15
HEADLESS = True  # Set to False to watch the agent work

# ============================================================


async def main():
    if not API_KEY:
        print("❌ No LLM API key. Check config.py or set BROWSER_USE_LLM_KEY.")
        sys.exit(1)

    llm = ChatOpenAI(model=MODEL, api_key=API_KEY, base_url=BASE_URL)

    agent = Agent(
        task=TASK,
        llm=llm,
        headless=HEADLESS,
    )

    print(f"Target:  {TARGET_URL}")
    print(f"Model:   {MODEL}")
    print(f"Steps:   {MAX_STEPS}")
    print(f"Headless: {HEADLESS}")
    print()

    result = await agent.run(max_steps=MAX_STEPS)

    print("\n" + "=" * 60)
    print("AGENT RESULT")
    print("=" * 60)
    # final_result() may return None on an incomplete run
    final = result.final_result() if hasattr(result, "final_result") else str(result)
    print(final or "(no result returned — run may be incomplete)")

    print("\n" + "=" * 60)
    print("STEPS TAKEN")
    print("=" * 60)
    for i, item in enumerate(result.history):
        if hasattr(item, "model_output") and item.model_output:
            actions = item.model_output.action
            if actions:
                action_desc = type(actions[0]).__name__ if actions else "?"
                print(f"  Step {i + 1}: {action_desc}")

    print(f"\nTotal steps: {len(result.history)}")
    # Guard against API differences across browser-use versions
    if hasattr(result, "is_done") and hasattr(result, "is_successful"):
        print(f"Success: {result.is_done() and result.is_successful()}")
    elif hasattr(result, "is_done"):
        print(f"Done: {result.is_done()}")


if __name__ == "__main__":
    asyncio.run(main())
